package com.example.bank.dao;

import com.example.bank.entity.Fj;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface FjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FJ
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FJ
     *
     * @mbggenerated
     */
    int insert(Fj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FJ
     *
     * @mbggenerated
     */
    int insertSelective(Fj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FJ
     *
     * @mbggenerated
     */
    Fj selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FJ
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Fj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FJ
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Fj record);

    List<Fj> selectByYwKey(String ywkey);
}