package com.example.bank.dao;

import com.example.bank.entity.Tbtj;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface TbtjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBTJ
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBTJ
     *
     * @mbggenerated
     */
    int insert(Tbtj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBTJ
     *
     * @mbggenerated
     */
    int insertSelective(Tbtj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBTJ
     *
     * @mbggenerated
     */
    Tbtj selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBTJ
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbtj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBTJ
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbtj record);

    List<Tbtj> selectAll();
}