package com.example.bank.dao;

import com.example.bank.entity.Yhkx;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface YhkxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YHKX
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YHKX
     *
     * @mbggenerated
     */
    int insert(Yhkx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YHKX
     *
     * @mbggenerated
     */
    int insertSelective(Yhkx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YHKX
     *
     * @mbggenerated
     */
    Yhkx selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YHKX
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Yhkx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YHKX
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Yhkx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YHKX
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Yhkx record);

    List<Yhkx> selectAll();
}