package com.example.bank.dao;

import com.example.bank.entity.Zhgg;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ZhggMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHGG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHGG
     *
     * @mbggenerated
     */
    int insert(Zhgg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHGG
     *
     * @mbggenerated
     */
    int insertSelective(Zhgg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHGG
     *
     * @mbggenerated
     */
    Zhgg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHGG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Zhgg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHGG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Zhgg record);
}