package com.example.bank.dao;

import com.example.bank.entity.Zhxw;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ZhxwMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHXW
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHXW
     *
     * @mbggenerated
     */
    int insert(Zhxw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHXW
     *
     * @mbggenerated
     */
    int insertSelective(Zhxw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHXW
     *
     * @mbggenerated
     */
    Zhxw selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHXW
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Zhxw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHXW
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Zhxw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHXW
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Zhxw record);

    List<Zhxw> selectAll();
}