package com.example.bank.entity;

public class Fj {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJ.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJ.ywkey
     *
     * @mbggenerated
     */
    private String ywkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJ.xdpath
     *
     * @mbggenerated
     */
    private String xdpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJ.filename
     *
     * @mbggenerated
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJ.ccmc
     *
     * @mbggenerated
     */
    private String ccmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FJ.wjdx
     *
     * @mbggenerated
     */
    private Integer wjdx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJ.id
     *
     * @return the value of FJ.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJ.id
     *
     * @param id the value for FJ.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJ.ywkey
     *
     * @return the value of FJ.ywkey
     *
     * @mbggenerated
     */
    public String getYwkey() {
        return ywkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJ.ywkey
     *
     * @param ywkey the value for FJ.ywkey
     *
     * @mbggenerated
     */
    public void setYwkey(String ywkey) {
        this.ywkey = ywkey == null ? null : ywkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJ.xdpath
     *
     * @return the value of FJ.xdpath
     *
     * @mbggenerated
     */
    public String getXdpath() {
        return xdpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJ.xdpath
     *
     * @param xdpath the value for FJ.xdpath
     *
     * @mbggenerated
     */
    public void setXdpath(String xdpath) {
        this.xdpath = xdpath == null ? null : xdpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJ.filename
     *
     * @return the value of FJ.filename
     *
     * @mbggenerated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJ.filename
     *
     * @param filename the value for FJ.filename
     *
     * @mbggenerated
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJ.ccmc
     *
     * @return the value of FJ.ccmc
     *
     * @mbggenerated
     */
    public String getCcmc() {
        return ccmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJ.ccmc
     *
     * @param ccmc the value for FJ.ccmc
     *
     * @mbggenerated
     */
    public void setCcmc(String ccmc) {
        this.ccmc = ccmc == null ? null : ccmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FJ.wjdx
     *
     * @return the value of FJ.wjdx
     *
     * @mbggenerated
     */
    public Integer getWjdx() {
        return wjdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FJ.wjdx
     *
     * @param wjdx the value for FJ.wjdx
     *
     * @mbggenerated
     */
    public void setWjdx(Integer wjdx) {
        this.wjdx = wjdx;
    }
}