package com.example.bank.entity;

public class Yhkx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YHKX.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YHKX.bt
     *
     * @mbggenerated
     */
    private String bt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YHKX.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YHKX.pic
     *
     * @mbggenerated
     */
    private byte[] pic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YHKX.id
     *
     * @return the value of YHKX.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YHKX.id
     *
     * @param id the value for YHKX.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YHKX.bt
     *
     * @return the value of YHKX.bt
     *
     * @mbggenerated
     */
    public String getBt() {
        return bt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YHKX.bt
     *
     * @param bt the value for YHKX.bt
     *
     * @mbggenerated
     */
    public void setBt(String bt) {
        this.bt = bt == null ? null : bt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YHKX.pid
     *
     * @return the value of YHKX.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YHKX.pid
     *
     * @param pid the value for YHKX.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YHKX.pic
     *
     * @return the value of YHKX.pic
     *
     * @mbggenerated
     */
    public byte[] getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YHKX.pic
     *
     * @param pic the value for YHKX.pic
     *
     * @mbggenerated
     */
    public void setPic(byte[] pic) {
        this.pic = pic;
    }
}