package com.example.bank.entity;

public class Zhgg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHGG.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHGG.fjid
     *
     * @mbggenerated
     */
    private Integer fjid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHGG.bt
     *
     * @mbggenerated
     */
    private String bt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHGG.id
     *
     * @return the value of ZHGG.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHGG.id
     *
     * @param id the value for ZHGG.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHGG.fjid
     *
     * @return the value of ZHGG.fjid
     *
     * @mbggenerated
     */
    public Integer getFjid() {
        return fjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHGG.fjid
     *
     * @param fjid the value for ZHGG.fjid
     *
     * @mbggenerated
     */
    public void setFjid(Integer fjid) {
        this.fjid = fjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHGG.bt
     *
     * @return the value of ZHGG.bt
     *
     * @mbggenerated
     */
    public String getBt() {
        return bt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHGG.bt
     *
     * @param bt the value for ZHGG.bt
     *
     * @mbggenerated
     */
    public void setBt(String bt) {
        this.bt = bt == null ? null : bt.trim();
    }
}